name: Microservice CI/CD

on:
  push:
    branches:
      - master

jobs:
  docker:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: SonarQube Scan - Backend
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.PAYMENT_BACKEND }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.projectKey=payment-backend   

      - name: SonarQube Scan - Frontend
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.PAYMENT_BACKEND }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: frontend
          args: >
            -Dsonar.projectKey=payment-frontend
            
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Auth Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest backend/auth_service

      - name: Build Payment Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest backend/payment_service

      - name: Build Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest frontend

      - name: Build Nginx
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest nginx

      - name: Push Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/payment-service:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest
:w
